### ISSUE TITLE
Error when trying to start eyeloop

### ISSUE THREAD

**Issue by alex-attinger** [simonarvin/eyeloop#27]
Hi, I just wanted to test eyeloop. I cloned the repository and then in a new conda environment ran 'pip install .' When I then run "eyeloop" I get a " No module named 'eyeloop.run_eyeloop' " error. Similarly, when I run python eyeloop\run_eyeloop.py, i get:  No module named 'eyeloop.config' . It seems like something is off with the paths, but I can't figure out what. Can you help?

**Comment by kinow** [comment]
I think #26 is duplicate of this. I've reproduced the problem

```
(venv) kinow@ranma:~/Development/python/workspace/eyeloop$ eyeloop
Traceback (most recent call last):
  File "/home/kinow/Development/python/workspace/eyeloop/venv/bin/eyeloop", line 11, in <module>
    load_entry_point('eyeloop==0.1', 'console_scripts', 'eyeloop')()
  File "/home/kinow/Development/python/workspace/eyeloop/venv/lib/python3.8/site-packages/pkg_resources/__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/home/kinow/Development/python/workspace/eyeloop/venv/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2852, in load_entry_point
    return ep.load()
  File "/home/kinow/Development/python/workspace/eyeloop/venv/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2443, in load
    return self.resolve()
  File "/home/kinow/Development/python/workspace/eyeloop/venv/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2449, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
ModuleNotFoundError: No module named 'eyeloop.run_eyeloop'

```

Which is strange, as this works.

```
(venv) kinow@ranma:~/Development/python/workspace/eyeloop$ python
Python 3.8.3 (default, May 19 2020, 18:47:26) 
[GCC 7.3.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import eyeloop
>>> from eyeloop import run_eyeloop
>>> 

```

**Comment by kinow** [comment]
See linked PR for a proposed fix :+1: :vulcan_salute:

**Comment by alex-attinger** [comment]
Thanks, it solved it for me
