### ISSUE TITLE
`AttributeError: 'int' object has no attribute 'frame'` importer.frame in frametimer.py

### ISSUE THREAD

**Issue by bhomaidan1990** [simonarvin/eyeloop#40]
In the `frametimer` in this [line](https://github.com/simonarvin/eyeloop/blob/master/eyeloop/extractors/frametimer.py#L22) you are importing the frame from the [importer](https://github.com/simonarvin/eyeloop/blob/master/eyeloop/config.py#L2) so I'm getting this error while trying to execute `eyeloop --importer cv/vimba`.

Full Traceback
```
2022-03-08 02:26:16,555 - eyeloop.engine.engine - INFO - loading extractors: [<eyeloop.extractors.frametimer.FPS_extractor object at 0x00000169EB573910>, <eyeloop.extractors.DAQ.DAQ_extractor object at 0x00000169EB573760>]
2022-03-08 02:26:16,555 - eyeloop.run_eyeloop - INFO - Initiating tracking via Importer: cv/vimba
2022-03-08 02:26:16,555 - eyeloop.run_eyeloop - ERROR - Invalid importer selected
Traceback (most recent call last):
  File "C:\Users\bhoma\AppData\Local\Programs\Python\Python38\lib\site-packages\eyeloop\run_eyeloop.py", line 99, in run_importer
    importer_module = importlib.import_module(f"eyeloop.importers.{config.arguments.importer}")
  File "C:\Users\bhoma\AppData\Local\Programs\Python\Python38\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'eyeloop.importers.cv/vimba'
Exception in thread Thread-1:
Traceback (most recent call last):
  File "C:\Users\bhoma\AppData\Local\Programs\Python\Python38\lib\threading.py", line 932, in _bootstrap_inner
    self.run()
  File "C:\Users\bhoma\AppData\Local\Programs\Python\Python38\lib\threading.py", line 1254, in run
    self.function(*self.args, **self.kwargs)
  File "C:\Users\bhoma\AppData\Local\Programs\Python\Python38\lib\site-packages\eyeloop\extractors\frametimer.py", line 21, in get_fps
    print(f"    Processing {config.importer.frame - self.last_frame} frames per second.")
AttributeError: 'int' object has no attribute 'frame'
```

**Comment by simonarvin** [comment]
Hi,

Your eyeloop command is incorrect. You should choose 1 importer, for example:

`eyeloop --importer cv`

Or

`eyeloop --importer vimba`

The cv importer works in most circumstances.

Best,
Simon
